"""Initial migrate

Revision ID: 12fde2bc39a5
Revises: 
Create Date: 2022-06-07 13:26:40.020021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12fde2bc39a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productname', sa.String(length=12), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_created_at'), 'sale', ['created_at'], unique=False)
    op.create_index(op.f('ix_sale_description'), 'sale', ['description'], unique=False)
    op.create_index(op.f('ix_sale_location'), 'sale', ['location'], unique=False)
    op.create_index(op.f('ix_sale_owner'), 'sale', ['owner'], unique=False)
    op.create_index(op.f('ix_sale_price'), 'sale', ['price'], unique=False)
    op.create_index(op.f('ix_sale_productname'), 'sale', ['productname'], unique=False)
    op.create_index(op.f('ix_sale_quantity'), 'sale', ['quantity'], unique=False)
    op.create_index(op.f('ix_sale_updated_at'), 'sale', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_updated_at'), table_name='sale')
    op.drop_index(op.f('ix_sale_quantity'), table_name='sale')
    op.drop_index(op.f('ix_sale_productname'), table_name='sale')
    op.drop_index(op.f('ix_sale_price'), table_name='sale')
    op.drop_index(op.f('ix_sale_owner'), table_name='sale')
    op.drop_index(op.f('ix_sale_location'), table_name='sale')
    op.drop_index(op.f('ix_sale_description'), table_name='sale')
    op.drop_index(op.f('ix_sale_created_at'), table_name='sale')
    op.drop_table('sale')
    # ### end Alembic commands ###
