"""store table

Revision ID: 52ebbb4c9eaa
Revises: 8a54ae205791
Create Date: 2022-03-26 20:15:48.820472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ebbb4c9eaa'
down_revision = '8a54ae205791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storename', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_region'), 'store', ['region'], unique=False)
    op.create_index(op.f('ix_store_storename'), 'store', ['storename'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_storename'), table_name='store')
    op.drop_index(op.f('ix_store_region'), table_name='store')
    op.drop_table('store')
    # ### end Alembic commands ###
