"""products update with location

Revision ID: 835de7da797a
Revises: 
Create Date: 2022-04-14 08:58:10.812081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835de7da797a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('location', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_product_location'), 'product', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_location'), table_name='product')
    op.drop_column('product', 'location')
    # ### end Alembic commands ###
