"""product name added to Products table.

Revision ID: 8a54ae205791
Revises: a1cb38b20267
Create Date: 2022-03-24 12:42:18.876501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a54ae205791'
down_revision = 'a1cb38b20267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('productname', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_product_productname'), 'product', ['productname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_productname'), table_name='product')
    op.drop_column('product', 'productname')
    # ### end Alembic commands ###
