"""orders & roducts  updated

Revision ID: c1f3ce29b234
Revises: 835de7da797a
Create Date: 2022-04-19 20:17:24.774348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f3ce29b234'
down_revision = '835de7da797a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'store', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'store_id')
    # ### end Alembic commands ###
