"""ordersTable

Revision ID: c68eb5268e2f
Revises: 12fde2bc39a5
Create Date: 2022-07-01 17:19:55.234212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68eb5268e2f'
down_revision = '12fde2bc39a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('comment', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_order_comment'), 'order', ['comment'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_comment'), table_name='order')
    op.drop_column('order', 'comment')
    # ### end Alembic commands ###
